package net.bigdataer.demo.log4j.logwriter;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adxlog.proto

public final class AdxWinLog {
  private AdxWinLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AdxLogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AdxLog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>optional string version = 1;</code>
     */
    String getVersion();
    /**
     * <code>optional string version = 1;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>required string displayId = 2;</code>
     */
    boolean hasDisplayId();
    /**
     * <code>required string displayId = 2;</code>
     */
    String getDisplayId();
    /**
     * <code>required string displayId = 2;</code>
     */
    com.google.protobuf.ByteString
        getDisplayIdBytes();

    /**
     * <code>optional string ts = 3;</code>
     */
    boolean hasTs();
    /**
     * <code>optional string ts = 3;</code>
     */
    String getTs();
    /**
     * <code>optional string ts = 3;</code>
     */
    com.google.protobuf.ByteString
        getTsBytes();

    /**
     * <code>optional string cookieId = 4;</code>
     */
    boolean hasCookieId();
    /**
     * <code>optional string cookieId = 4;</code>
     */
    String getCookieId();
    /**
     * <code>optional string cookieId = 4;</code>
     */
    com.google.protobuf.ByteString
        getCookieIdBytes();

    /**
     * <code>optional string imei = 5;</code>
     */
    boolean hasImei();
    /**
     * <code>optional string imei = 5;</code>
     */
    String getImei();
    /**
     * <code>optional string imei = 5;</code>
     */
    com.google.protobuf.ByteString
        getImeiBytes();

    /**
     * <code>optional string idfa = 6;</code>
     */
    boolean hasIdfa();
    /**
     * <code>optional string idfa = 6;</code>
     */
    String getIdfa();
    /**
     * <code>optional string idfa = 6;</code>
     */
    com.google.protobuf.ByteString
        getIdfaBytes();

    /**
     * <code>optional string sessionId = 7;</code>
     */
    boolean hasSessionId();
    /**
     * <code>optional string sessionId = 7;</code>
     */
    String getSessionId();
    /**
     * <code>optional string sessionId = 7;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>optional string userId = 8;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional string userId = 8;</code>
     */
    String getUserId();
    /**
     * <code>optional string userId = 8;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional string httpxForward = 9;</code>
     */
    boolean hasHttpxForward();
    /**
     * <code>optional string httpxForward = 9;</code>
     */
    String getHttpxForward();
    /**
     * <code>optional string httpxForward = 9;</code>
     */
    com.google.protobuf.ByteString
        getHttpxForwardBytes();

    /**
     * <code>optional string requestSource = 10;</code>
     */
    boolean hasRequestSource();
    /**
     * <code>optional string requestSource = 10;</code>
     */
    String getRequestSource();
    /**
     * <code>optional string requestSource = 10;</code>
     */
    com.google.protobuf.ByteString
        getRequestSourceBytes();
  }
  /**
   * Protobuf type {@code AdxLog}
   */
  public static final class AdxLog extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AdxLog)
      AdxLogOrBuilder {
    // Use AdxLog.newBuilder() to construct.
    private AdxLog(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AdxLog(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AdxLog defaultInstance;
    public static AdxLog getDefaultInstance() {
      return defaultInstance;
    }

    public AdxLog getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AdxLog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              version_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              displayId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              ts_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              cookieId_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              imei_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              idfa_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              sessionId_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              userId_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              httpxForward_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              requestSource_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AdxWinLog.internal_static_AdxLog_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AdxWinLog.internal_static_AdxLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AdxLog.class, Builder.class);
    }

    public static com.google.protobuf.Parser<AdxLog> PARSER =
        new com.google.protobuf.AbstractParser<AdxLog>() {
      public AdxLog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdxLog(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<AdxLog> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private Object version_;
    /**
     * <code>optional string version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string version = 1;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string version = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISPLAYID_FIELD_NUMBER = 2;
    private Object displayId_;
    /**
     * <code>required string displayId = 2;</code>
     */
    public boolean hasDisplayId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string displayId = 2;</code>
     */
    public String getDisplayId() {
      Object ref = displayId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          displayId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string displayId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayIdBytes() {
      Object ref = displayId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        displayId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TS_FIELD_NUMBER = 3;
    private Object ts_;
    /**
     * <code>optional string ts = 3;</code>
     */
    public boolean hasTs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string ts = 3;</code>
     */
    public String getTs() {
      Object ref = ts_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ts_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ts = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTsBytes() {
      Object ref = ts_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ts_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COOKIEID_FIELD_NUMBER = 4;
    private Object cookieId_;
    /**
     * <code>optional string cookieId = 4;</code>
     */
    public boolean hasCookieId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string cookieId = 4;</code>
     */
    public String getCookieId() {
      Object ref = cookieId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cookieId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cookieId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCookieIdBytes() {
      Object ref = cookieId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cookieId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMEI_FIELD_NUMBER = 5;
    private Object imei_;
    /**
     * <code>optional string imei = 5;</code>
     */
    public boolean hasImei() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string imei = 5;</code>
     */
    public String getImei() {
      Object ref = imei_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imei_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string imei = 5;</code>
     */
    public com.google.protobuf.ByteString
        getImeiBytes() {
      Object ref = imei_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        imei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDFA_FIELD_NUMBER = 6;
    private Object idfa_;
    /**
     * <code>optional string idfa = 6;</code>
     */
    public boolean hasIdfa() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string idfa = 6;</code>
     */
    public String getIdfa() {
      Object ref = idfa_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          idfa_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string idfa = 6;</code>
     */
    public com.google.protobuf.ByteString
        getIdfaBytes() {
      Object ref = idfa_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        idfa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSIONID_FIELD_NUMBER = 7;
    private Object sessionId_;
    /**
     * <code>optional string sessionId = 7;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string sessionId = 7;</code>
     */
    public String getSessionId() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sessionId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 8;
    private Object userId_;
    /**
     * <code>optional string userId = 8;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string userId = 8;</code>
     */
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userId = 8;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HTTPXFORWARD_FIELD_NUMBER = 9;
    private Object httpxForward_;
    /**
     * <code>optional string httpxForward = 9;</code>
     */
    public boolean hasHttpxForward() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string httpxForward = 9;</code>
     */
    public String getHttpxForward() {
      Object ref = httpxForward_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          httpxForward_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string httpxForward = 9;</code>
     */
    public com.google.protobuf.ByteString
        getHttpxForwardBytes() {
      Object ref = httpxForward_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        httpxForward_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTSOURCE_FIELD_NUMBER = 10;
    private Object requestSource_;
    /**
     * <code>optional string requestSource = 10;</code>
     */
    public boolean hasRequestSource() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string requestSource = 10;</code>
     */
    public String getRequestSource() {
      Object ref = requestSource_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestSource_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string requestSource = 10;</code>
     */
    public com.google.protobuf.ByteString
        getRequestSourceBytes() {
      Object ref = requestSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        requestSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = "";
      displayId_ = "";
      ts_ = "";
      cookieId_ = "";
      imei_ = "";
      idfa_ = "";
      sessionId_ = "";
      userId_ = "";
      httpxForward_ = "";
      requestSource_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDisplayId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getVersionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDisplayIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTsBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCookieIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getImeiBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getIdfaBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getHttpxForwardBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getRequestSourceBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getVersionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDisplayIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTsBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCookieIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getImeiBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getIdfaBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getHttpxForwardBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getRequestSourceBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static AdxLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AdxLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AdxLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AdxLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AdxLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AdxLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static AdxLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static AdxLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static AdxLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AdxLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(AdxLog prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AdxLog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AdxLog)
        AdxLogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AdxWinLog.internal_static_AdxLog_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AdxWinLog.internal_static_AdxLog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AdxLog.class, Builder.class);
      }

      // Construct using AdxWinLog.AdxLog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        displayId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ts_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        cookieId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        imei_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        idfa_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        httpxForward_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        requestSource_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AdxWinLog.internal_static_AdxLog_descriptor;
      }

      public AdxLog getDefaultInstanceForType() {
        return AdxLog.getDefaultInstance();
      }

      public AdxLog buildPartial() {
        AdxLog result = new AdxLog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.displayId_ = displayId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cookieId_ = cookieId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.imei_ = imei_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.idfa_ = idfa_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.httpxForward_ = httpxForward_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.requestSource_ = requestSource_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public AdxLog build() {
        AdxLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AdxLog) {
          return mergeFrom((AdxLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AdxLog other) {
        if (other == AdxLog.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          bitField0_ |= 0x00000001;
          version_ = other.version_;
          onChanged();
        }
        if (other.hasDisplayId()) {
          bitField0_ |= 0x00000002;
          displayId_ = other.displayId_;
          onChanged();
        }
        if (other.hasTs()) {
          bitField0_ |= 0x00000004;
          ts_ = other.ts_;
          onChanged();
        }
        if (other.hasCookieId()) {
          bitField0_ |= 0x00000008;
          cookieId_ = other.cookieId_;
          onChanged();
        }
        if (other.hasImei()) {
          bitField0_ |= 0x00000010;
          imei_ = other.imei_;
          onChanged();
        }
        if (other.hasIdfa()) {
          bitField0_ |= 0x00000020;
          idfa_ = other.idfa_;
          onChanged();
        }
        if (other.hasSessionId()) {
          bitField0_ |= 0x00000040;
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.hasUserId()) {
          bitField0_ |= 0x00000080;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasHttpxForward()) {
          bitField0_ |= 0x00000100;
          httpxForward_ = other.httpxForward_;
          onChanged();
        }
        if (other.hasRequestSource()) {
          bitField0_ |= 0x00000200;
          requestSource_ = other.requestSource_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDisplayId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AdxLog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AdxLog) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object version_ = "";
      /**
       * <code>optional string version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string version = 1;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string version = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string version = 1;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 1;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }

      private Object displayId_ = "";
      /**
       * <code>required string displayId = 2;</code>
       */
      public boolean hasDisplayId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string displayId = 2;</code>
       */
      public String getDisplayId() {
        Object ref = displayId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            displayId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string displayId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDisplayIdBytes() {
        Object ref = displayId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          displayId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string displayId = 2;</code>
       */
      public Builder setDisplayId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        displayId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string displayId = 2;</code>
       */
      public Builder clearDisplayId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        displayId_ = getDefaultInstance().getDisplayId();
        onChanged();
        return this;
      }
      /**
       * <code>required string displayId = 2;</code>
       */
      public Builder setDisplayIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        displayId_ = value;
        onChanged();
        return this;
      }

      private Object ts_ = "";
      /**
       * <code>optional string ts = 3;</code>
       */
      public boolean hasTs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string ts = 3;</code>
       */
      public String getTs() {
        Object ref = ts_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ts_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string ts = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTsBytes() {
        Object ref = ts_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ts_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ts = 3;</code>
       */
      public Builder setTs(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ts = 3;</code>
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ts_ = getDefaultInstance().getTs();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ts = 3;</code>
       */
      public Builder setTsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ts_ = value;
        onChanged();
        return this;
      }

      private Object cookieId_ = "";
      /**
       * <code>optional string cookieId = 4;</code>
       */
      public boolean hasCookieId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string cookieId = 4;</code>
       */
      public String getCookieId() {
        Object ref = cookieId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cookieId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string cookieId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCookieIdBytes() {
        Object ref = cookieId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cookieId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cookieId = 4;</code>
       */
      public Builder setCookieId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        cookieId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cookieId = 4;</code>
       */
      public Builder clearCookieId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cookieId_ = getDefaultInstance().getCookieId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cookieId = 4;</code>
       */
      public Builder setCookieIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        cookieId_ = value;
        onChanged();
        return this;
      }

      private Object imei_ = "";
      /**
       * <code>optional string imei = 5;</code>
       */
      public boolean hasImei() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string imei = 5;</code>
       */
      public String getImei() {
        Object ref = imei_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            imei_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string imei = 5;</code>
       */
      public com.google.protobuf.ByteString
          getImeiBytes() {
        Object ref = imei_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          imei_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string imei = 5;</code>
       */
      public Builder setImei(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        imei_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string imei = 5;</code>
       */
      public Builder clearImei() {
        bitField0_ = (bitField0_ & ~0x00000010);
        imei_ = getDefaultInstance().getImei();
        onChanged();
        return this;
      }
      /**
       * <code>optional string imei = 5;</code>
       */
      public Builder setImeiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        imei_ = value;
        onChanged();
        return this;
      }

      private Object idfa_ = "";
      /**
       * <code>optional string idfa = 6;</code>
       */
      public boolean hasIdfa() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string idfa = 6;</code>
       */
      public String getIdfa() {
        Object ref = idfa_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            idfa_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string idfa = 6;</code>
       */
      public com.google.protobuf.ByteString
          getIdfaBytes() {
        Object ref = idfa_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          idfa_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string idfa = 6;</code>
       */
      public Builder setIdfa(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        idfa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string idfa = 6;</code>
       */
      public Builder clearIdfa() {
        bitField0_ = (bitField0_ & ~0x00000020);
        idfa_ = getDefaultInstance().getIdfa();
        onChanged();
        return this;
      }
      /**
       * <code>optional string idfa = 6;</code>
       */
      public Builder setIdfaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        idfa_ = value;
        onChanged();
        return this;
      }

      private Object sessionId_ = "";
      /**
       * <code>optional string sessionId = 7;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string sessionId = 7;</code>
       */
      public String getSessionId() {
        Object ref = sessionId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sessionId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string sessionId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessionId = 7;</code>
       */
      public Builder setSessionId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionId = 7;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionId = 7;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        sessionId_ = value;
        onChanged();
        return this;
      }

      private Object userId_ = "";
      /**
       * <code>optional string userId = 8;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string userId = 8;</code>
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string userId = 8;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userId = 8;</code>
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 8;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 8;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        userId_ = value;
        onChanged();
        return this;
      }

      private Object httpxForward_ = "";
      /**
       * <code>optional string httpxForward = 9;</code>
       */
      public boolean hasHttpxForward() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string httpxForward = 9;</code>
       */
      public String getHttpxForward() {
        Object ref = httpxForward_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            httpxForward_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string httpxForward = 9;</code>
       */
      public com.google.protobuf.ByteString
          getHttpxForwardBytes() {
        Object ref = httpxForward_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          httpxForward_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string httpxForward = 9;</code>
       */
      public Builder setHttpxForward(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        httpxForward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string httpxForward = 9;</code>
       */
      public Builder clearHttpxForward() {
        bitField0_ = (bitField0_ & ~0x00000100);
        httpxForward_ = getDefaultInstance().getHttpxForward();
        onChanged();
        return this;
      }
      /**
       * <code>optional string httpxForward = 9;</code>
       */
      public Builder setHttpxForwardBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        httpxForward_ = value;
        onChanged();
        return this;
      }

      private Object requestSource_ = "";
      /**
       * <code>optional string requestSource = 10;</code>
       */
      public boolean hasRequestSource() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string requestSource = 10;</code>
       */
      public String getRequestSource() {
        Object ref = requestSource_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            requestSource_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string requestSource = 10;</code>
       */
      public com.google.protobuf.ByteString
          getRequestSourceBytes() {
        Object ref = requestSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          requestSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestSource = 10;</code>
       */
      public Builder setRequestSource(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        requestSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestSource = 10;</code>
       */
      public Builder clearRequestSource() {
        bitField0_ = (bitField0_ & ~0x00000200);
        requestSource_ = getDefaultInstance().getRequestSource();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestSource = 10;</code>
       */
      public Builder setRequestSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        requestSource_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AdxLog)
    }

    static {
      defaultInstance = new AdxLog(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AdxLog)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AdxLog_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AdxLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014adxlog.proto\"\266\001\n\006AdxLog\022\017\n\007version\030\001 \001" +
      "(\t\022\021\n\tdisplayId\030\002 \002(\t\022\n\n\002ts\030\003 \001(\t\022\020\n\010coo" +
      "kieId\030\004 \001(\t\022\014\n\004imei\030\005 \001(\t\022\014\n\004idfa\030\006 \001(\t\022" +
      "\021\n\tsessionId\030\007 \001(\t\022\016\n\006userId\030\010 \001(\t\022\024\n\014ht" +
      "tpxForward\030\t \001(\t\022\025\n\rrequestSource\030\n \001(\tB" +
      "\013B\tAdxWinLog"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AdxLog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AdxLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AdxLog_descriptor,
        new String[] { "Version", "DisplayId", "Ts", "CookieId", "Imei", "Idfa", "SessionId", "UserId", "HttpxForward", "RequestSource", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
